version: '3.0'

services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'semillero/server'
    ports:
      - '8080:8080'
    volumes:
      - ./imagenes:/tmp/:rw
    command: python3 server.py
    environment:
      PYTHONUNBUFFERED : 1